In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Social_Network_Ads.csv")
data.count()

User ID            400
Gender             400
Age                400
EstimatedSalary    400
Purchased          400
dtype: int64

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
data.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
dummy = pd.get_dummies(data["Gender"]).iloc[:,1:2] 
data1 = data.copy()

In [6]:
data1 = data1.drop(["Gender","Purchased"],axis=1)
last_data = pd.concat([data1,dummy],axis = 1)
last_data.head()

User ID  Age  EstimatedSalary  Male
0  15624510   19            19000     1
1  15810944   35            20000     1
2  15668575   26            43000     0
3  15603246   27            57000     0
4  15804002   19            76000     1

In [7]:
y = data.iloc[:,4:5].values
x = last_data.iloc[:,1:3].values

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
sc = StandardScaler()
x_scaled = sc.fit_transform(x)
x_scaled1 = pd.DataFrame(x_scaled)
print(x_scaled1)

            0         1
0   -1.781797 -1.490046
1   -0.253587 -1.460681
2   -1.113206 -0.785290
3   -1.017692 -0.374182
4   -1.781797  0.183751
..        ...       ...
395  0.797057 -0.844019
396  1.274623 -1.372587
397  1.179110 -1.460681
398 -0.158074 -1.078938
399  1.083596 -0.990844

[400 rows x 2 columns]


In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.33)

In [12]:
x_test

array([[-1.11320552,  0.30121002],
       [-1.01769239, -1.54877595],
       [ 1.65667523, -0.9027491 ],
       [ 1.5611621 ,  1.123426  ],
       [ 0.70154394, -0.72655996],
       [-1.11320552,  0.33057487],
       [ 0.31949142,  0.06629116],
       [-1.78179743,  0.00756145],
       [-0.34910049, -0.78528968],
       [ 0.03295203, -0.13926283],
       [ 1.37013584,  2.35674998],
       [-0.25358736,  0.21311545],
       [-1.01769239,  0.53612887],
       [-0.15807423, -1.07893824],
       [ 0.60603081,  2.03373655],
       [ 0.89257019,  1.09406114],
       [ 0.31949142, -1.16703281],
       [-0.92217926,  1.56389885],
       [-0.0625611 ,  0.30121002],
       [ 2.03872775,  0.18375059],
       [-0.25358736,  0.15438573],
       [ 0.22397829,  1.09406114],
       [ 0.98808332, -1.16703281],
       [-0.0625611 , -1.07893824],
       [ 0.41500455, -0.13926283],
       [ 0.31949142, -0.55037082],
       [-0.15807423,  0.85914229],
       [ 0.79705706,  0.12502088],
       [-0.25358736,

In [13]:
from sklearn.svm import SVC

In [14]:
svc = SVC(kernel="rbf")
svc.fit(x_train, y_train)

/home/mert/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [15]:
print("test accuracy {}".format(svc.score(x_test,y_test)))
print("train accuracy {}".format(svc.score(x_train, y_train)))

test accuracy 0.9166666666666666
train accuracy 0.9104477611940298


In [16]:
import statsmodels.api as sm
from sklearn.metrics import confusion_matrix

In [17]:
model = sm.OLS(svc.predict(x_test),x_test)
print(model.fit().summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.397
Model:                            OLS   Adj. R-squared (uncentered):              0.388
Method:                 Least Squares   F-statistic:                              42.87
Date:                Sat, 20 Nov 2021   Prob (F-statistic):                    5.03e-15
Time:                        19:08:57   Log-Likelihood:                         -92.387
No. Observations:                 132   AIC:                                      188.8
Df Residuals:                     130   BIC:                                      194.5
Df Model:                           2                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [18]:
con = confusion_matrix(svc.predict(x_test), y_test)
print(con)

[[76  4]
 [ 7 45]]


In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
cvs = cross_val_score(estimator= svc, X= x_train, y= y_train, cv= 3)
print(cvs.mean())

0.9030378693300042


/home/mert/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/home/mert/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/home/mert/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [21]:
from sklearn.model_selection import GridSearchCV
p = [{'C':[1,2,3,4,5],'kernel':['linear']},
     {'C':[1,2,3,4,5] ,'kernel':['rbf'],
      'gamma':[1,0.5,0.1,0.01,0.001]} ]

'''
GSCV parameters
estimator : classification algorithm 
param_grid : parameters
scoring: scoring, for example: accuracy
cv : cv
n_jobs : number of jobs
'''
gs = GridSearchCV(estimator= svc, #SVM algoritması
                  param_grid = p,
                  scoring =  'accuracy',
                  cv = 2,
                  n_jobs = -1)

grid_search = gs.fit(x_train,y_train)
TheBestScore = grid_search.best_score_
TheBestParameters = grid_search.best_params_

print(TheBestScore)
print(TheBestParameters)


0.8992537313432836
{'C': 1, 'gamma': 0.5, 'kernel': 'rbf'}


/home/mert/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [23]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train, y_train)
y_pred_x = classifier.predict(x_test)

/home/mert/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/mert/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


[19:10:20] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [25]:
cm_xgb = confusion_matrix(y_test, y_pred_x)
print(cm_xgb)

[[76  7]
 [ 8 41]]
